language: python

python:
    - "3.5"
    - "3.4"
    - "2.7"
    - "pypy"

install:
    - pip install cookiecutter

script:
    - cookiecutter . --no-input
    - python ./python_boilerplate/docs/github_docs.py
    - cd ./python_boilerplate && python setup.py test
